// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebyYnji1ghbPrPTlcYDhJcdJ5LuAnjUY',
    appId: '1:235385413470:android:ead55d840a781a6a5bb9cf',
    messagingSenderId: '235385413470',
    projectId: 'aura-b81ec',
    storageBucket: 'aura-b81ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXbNiPHmsUnhI2jf_FsOmFYtrau9mfsg',
    appId: '1:235385413470:ios:ccc9fbc918247f655bb9cf',
    messagingSenderId: '235385413470',
    projectId: 'aura-b81ec',
    storageBucket: 'aura-b81ec.appspot.com',
    androidClientId: '235385413470-eulctd6gbrh6di5gk666oule5h3ku7sc.apps.googleusercontent.com',
    iosClientId: '235385413470-0nn8crelni11bfb17r3tcco7snbskjmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aura',
  );

}